//
//  Champion.swift
//  GMakers
//
//  Created by Lee on 2021/09/12.
//

import Foundation

class ChampionManager {
  
  struct Champion {
    let intial: String
    let ko: String
    let en: String
    let tag: Int
  }
  
  static let allData: [Champion] = [
    Champion(intial: "ㅇ", ko: "아트록스", en: "Aatrox", tag: 266),
    Champion(intial: "ㅇ", ko: "아리", en: "Ahri", tag: 103),
    Champion(intial: "ㅇ", ko: "아칼리", en: "Akali", tag: 84),
//    Akshan 166
    Champion(intial: "ㅇ", ko: "알리스타", en: "Alistar", tag: 12),
    Champion(intial: "ㅇ", ko: "아무무", en: "Amumu", tag: 32),
    Champion(intial: "ㅇ", ko: "애니비아", en: "Anivia", tag: 34),
    Champion(intial: "ㅇ", ko: "애니", en: "Annie", tag: 1),
    Champion(intial: "ㅇ", ko: "아펠리우스", en: "Aphelios", tag: 523),
    Champion(intial: "ㅇ", ko: "애쉬", en: "Ashe", tag: 22),
    Champion(intial: "ㅇ", ko: "아우렐리온솔", en: "AurelionSol", tag: 136),
    Champion(intial: "ㅇ", ko: "아지르", en: "Azir", tag: 268),
    Champion(intial: "ㅂ", ko: "바드", en: "Bard", tag: 432),
    Champion(intial: "ㅂ", ko: "블리츠크랭크", en: "Blitzcrank", tag: 53),
    Champion(intial: "ㅂ", ko: "브랜드", en: "Brand", tag: 63),
    Champion(intial: "ㅂ", ko: "브라운", en: "Braum", tag: 201),
    Champion(intial: "ㅋ", ko: "케이틀린", en: "Caitlyn", tag: 51),
    Champion(intial: "ㅋ", ko: "카밀", en: "Camille", tag: 164),
    Champion(intial: "ㅋ", ko: "카시오페아", en: "Cassiopeia", tag: 69),
    Champion(intial: "ㅊ", ko: "초가스", en: "Chogath", tag: 31),
    Champion(intial: "ㅋ", ko: "코르키", en: "Corki", tag: 42),
    Champion(intial: "ㄷ", ko: "다리우스", en: "Darius", tag: 122),
    Champion(intial: "ㄷ", ko: "다이애나", en: "Diana", tag: 131),
    Champion(intial: "ㄷ", ko: "드레이브", en: "Draven", tag: 119),
    Champion(intial: "ㅁ", ko: "문도박사", en: "DrMundo", tag: 36),
    Champion(intial: "ㅇ", ko: "에코", en: "Ekko", tag: 245),
    Champion(intial: "ㅇ", ko: "엘리스", en: "Elise", tag: 60),
    Champion(intial: "ㅇ", ko: "이블린", en: "Evelynn", tag: 28),
    Champion(intial: "ㅇ", ko: "이즈리얼", en: "Ezreal", tag: 81),
    Champion(intial: "ㅍ", ko: "피들스틱", en: "Fiddlesticks", tag: 9),
    Champion(intial: "ㅍ", ko: "피오라", en: "Fiora", tag: 114),
    Champion(intial: "ㅍ", ko: "피즈", en: "Fizz", tag: 105),
    Champion(intial: "ㄱ", ko: "갈리오", en: "Galio", tag: 3),
    Champion(intial: "ㄱ", ko: "갱플랭크", en: "Gangplank", tag: 41),
    Champion(intial: "ㄱ", ko: "가랜", en: "Garen", tag: 86),
    Champion(intial: "ㄴ", ko: "나르", en: "Gnar", tag: 150),
    Champion(intial: "ㄱ", ko: "그라가스", en: "Gragas", tag: 79),
    Champion(intial: "ㄱ", ko: "그래이브즈", en: "Graves", tag: 104),
//    Gwen 887
    Champion(intial: "ㅎ", ko: "헤카림", en: "Hecarim", tag: 120),
    Champion(intial: "ㅎ", ko: "하이머딩거", en: "Heimerdinger", tag: 74),
    Champion(intial: "ㅇ", ko: "일라오이", en: "Illaoi", tag: 420),
    Champion(intial: "ㅇ", ko: "이렐리아", en: "Irelia", tag: 39),
    Champion(intial: "ㅇ", ko: "아이번", en: "Ivern", tag: 427),
    Champion(intial: "ㅈ", ko: "잔나", en: "Janna", tag: 40),
    Champion(intial: "ㅈ", ko: "자르반4세", en: "JarvanIV", tag: 59),
    Champion(intial: "ㅈ", ko: "잭스", en: "Jax", tag: 24),
    Champion(intial: "ㅈ", ko: "제이스", en: "Jayce", tag: 126),
    Champion(intial: "ㅈ", ko: "진", en: "Jhin", tag: 202),
    Champion(intial: "ㅈ", ko: "징크스", en: "Jinx", tag: 222),
    Champion(intial: "ㅋ", ko: "카이사", en: "Kaisa", tag: 145),
    Champion(intial: "ㅋ", ko: "칼리스타", en: "Kalista", tag: 429),
    Champion(intial: "ㅋ", ko: "카르마", en: "Karma", tag: 43),
    Champion(intial: "ㅋ", ko: "카서스", en: "Karthus", tag: 30),
    Champion(intial: "ㅋ", ko: "카사딘", en: "Kassadin", tag: 38),
    Champion(intial: "ㅋ", ko: "카타리나", en: "Katarina", tag: 55),
    Champion(intial: "ㅋ", ko: "케일", en: "Kayle", tag: 10),
    Champion(intial: "ㅋ", ko: "케인", en: "Kayn", tag: 141),
    Champion(intial: "ㅋ", ko: "케넨", en: "Kennen", tag: 85),
    Champion(intial: "ㅋ", ko: "카직스", en: "Khazix", tag: 121),
    Champion(intial: "ㅋ", ko: "킨드레드", en: "Kindred", tag: 203),
    Champion(intial: "ㅋ", ko: "클리드", en: "Kled", tag: 240),
    Champion(intial: "ㅋ", ko: "코그모", en: "KogMaw", tag: 96),
    Champion(intial: "ㄹ", ko: "르블랑", en: "Leblanc", tag: 7),
    Champion(intial: "ㄹ", ko: "리 신", en: "LeeSin", tag: 64),
    Champion(intial: "ㄹ", ko: "레오나", en: "Leona", tag: 89),
//    Lillia 876
    Champion(intial: "ㄹ", ko: "리산드라", en: "Lissandra", tag: 127),
    Champion(intial: "ㄹ", ko: "루시안", en: "Lucian", tag: 236),
    Champion(intial: "ㄹ", ko: "룰루", en: "Lulu", tag: 117),
    Champion(intial: "ㄹ", ko: "럭스", en: "Lux", tag: 99),
    Champion(intial: "ㅁ", ko: "말파이트", en: "Malphite", tag: 54),
    Champion(intial: "ㅁ", ko: "말자하", en: "Malzahar", tag: 90),
    Champion(intial: "ㅁ", ko: "마오카이", en: "Maokai", tag: 57),
    Champion(intial: "ㅁ", ko: "마스터이", en: "MasterYi", tag: 11),
    Champion(intial: "ㅁ", ko: "미스포춘", en: "MissFortune", tag: 21),
    Champion(intial: "ㅇ", ko: "오공", en: "MonkeyKing", tag: 62),
    Champion(intial: "ㅁ", ko: "모데카이", en: "Mordekaiser", tag: 82),
    Champion(intial: "ㅁ", ko: "모르가나", en: "Morgana", tag: 25),
    Champion(intial: "ㄴ", ko: "나미", en: "Nami", tag: 267),
    Champion(intial: "ㄴ", ko: "나서스", en: "Nasus", tag: 75),
    Champion(intial: "ㄴ", ko: "노틸러스", en: "Nautilus", tag: 111),
    Champion(intial: "ㄴ", ko: "니코", en: "Neeko", tag: 518),
    Champion(intial: "ㄴ", ko: "니달리", en: "Nidalee", tag: 76),
    Champion(intial: "ㄴ", ko: "녹턴", en: "Nocturne", tag: 56),
    Champion(intial: "ㄴ", ko: "누누", en: "Nunu", tag: 20),
    Champion(intial: "ㅇ", ko: "울라프", en: "Olaf", tag: 2),
    Champion(intial: "ㅇ", ko: "오리아나", en: "Orianna", tag: 61),
    Champion(intial: "ㅇ", ko: "오른", en: "Ornn", tag: 516),
    Champion(intial: "ㅍ", ko: "판테온", en: "Pantheon", tag: 80),
    Champion(intial: "ㅂ", ko: "뽀삐", en: "Poppy", tag: 78),
    Champion(intial: "ㅍ", ko: "파이크", en: "Pyke", tag: 555),
    Champion(intial: "ㅋ", ko: "키아나", en: "Qiyana", tag: 246),
    Champion(intial: "ㅋ", ko: "퀸", en: "Quinn", tag: 133),
    Champion(intial: "ㄹ", ko: "라칸", en: "Rakan", tag: 497),
    Champion(intial: "ㄹ", ko: "람머스", en: "Rammus", tag: 33),
    Champion(intial: "ㄹ", ko: "렉사이", en: "RekSai", tag: 421),
//    Rell 526
    Champion(intial: "ㄹ", ko: "레넥톤", en: "Renekton", tag: 58),
    Champion(intial: "ㄹ", ko: "랭가", en: "Rengar", tag: 107),
    Champion(intial: "ㄹ", ko: "리븐", en: "Riven", tag: 92),
    Champion(intial: "ㄹ", ko: "럼블", en: "Rumble", tag: 68),
    Champion(intial: "ㄹ", ko: "라이즈", en: "Ryze", tag: 13),
//    Samira 360
    Champion(intial: "ㅅ", ko: "세주아니", en: "Sejuani", tag: 113),
    Champion(intial: "ㅅ", ko: "세나", en: "Senna", tag: 235),
//    Seraphine 147
    Champion(intial: "ㅅ", ko: "세트", en: "Sett", tag: 875),
    Champion(intial: "ㅅ", ko: "샤코", en: "Shaco", tag: 35),
    Champion(intial: "ㅅ", ko: "쉔", en: "Shen", tag: 98),
    Champion(intial: "ㅅ", ko: "쉬바나", en: "Shyvana", tag: 102),
    Champion(intial: "ㅅ", ko: "신지드", en: "Singed", tag: 27),
    Champion(intial: "ㅅ", ko: "사이나", en: "Sion", tag: 14),
    Champion(intial: "ㅅ", ko: "시비르", en: "Sivir", tag: 15),
    Champion(intial: "ㅅ", ko: "스카너", en: "Skarner", tag: 72),
    Champion(intial: "ㅅ", ko: "소나", en: "Sona", tag: 37),
    Champion(intial: "ㅅ", ko: "소라카", en: "Soraka", tag: 16),
    Champion(intial: "ㅅ", ko: "스웨인", en: "Swain", tag: 50),
    Champion(intial: "ㅅ", ko: "사일러스", en: "Sylas", tag: 517),
    Champion(intial: "ㅅ", ko: "신드라", en: "Syndra", tag: 124),
    Champion(intial: "ㅌ", ko: "탐캔치", en: "TahmKench", tag: 223),
    Champion(intial: "ㅌ", ko: "탈리야", en: "Taliyah", tag: 163),
    Champion(intial: "ㅌ", ko: "탈론", en: "Talon", tag: 91),
    Champion(intial: "ㅌ", ko: "타릭", en: "Taric", tag: 44),
    Champion(intial: "ㅌ", ko: "티모", en: "Teemo", tag: 17),
    Champion(intial: "ㅅ", ko: "쓰레쉬", en: "Thresh", tag: 412),
    Champion(intial: "ㅌ", ko: "트리스타나", en: "Tristana", tag: 18),
    Champion(intial: "ㅌ", ko: "트런들", en: "Trundle", tag: 48),
    Champion(intial: "ㅌ", ko: "트린다이머", en: "Tryndamere", tag: 23),
    Champion(intial: "ㅌ", ko: "트위스티드 페이트", en: "TwistedFate", tag: 4),
    Champion(intial: "ㅌ", ko: "트위치", en: "Twitch", tag: 29),
    Champion(intial: "ㅇ", ko: "우디르", en: "Udyr", tag: 77),
    Champion(intial: "ㅇ", ko: "우르곳", en: "Urgot", tag: 6),
    Champion(intial: "ㅂ", ko: "바루스", en: "Varus", tag: 110),
    Champion(intial: "ㅂ", ko: "베인", en: "Vayne", tag: 67),
    Champion(intial: "ㅂ", ko: "베이가", en: "Veigar", tag: 45),
    Champion(intial: "ㅂ", ko: "벨코즈", en: "Velkoz", tag: 161),
    Champion(intial: "ㅂ", ko: "바이", en: "Vi", tag: 254),
//    Viego 234
    Champion(intial: "ㅂ", ko: "빅토르", en: "Viktor", tag: 112),
    Champion(intial: "ㅂ", ko: "블라디미르", en: "Vladimir", tag: 8),
    Champion(intial: "ㅂ", ko: "볼리베어", en: "Volibear", tag: 106),
    Champion(intial: "ㅇ", ko: "워윅", en: "Warwick", tag: 19),
    Champion(intial: "ㅈ", ko: "자야", en: "Xayah", tag: 498),
    Champion(intial: "ㅈ", ko: "제라스", en: "Xerath", tag: 101),
    Champion(intial: "ㅅ", ko: "신짜오", en: "XinZhao", tag: 5),
    Champion(intial: "ㅇ", ko: "야스오", en: "Yasuo", tag: 157),
    Champion(intial: "ㅇ", ko: "요릭", en: "Yorick", tag: 83),
    Champion(intial: "ㅇ", ko: "유미", en: "Yuumi", tag: 350),
    Champion(intial: "ㅈ", ko: "자크", en: "Zac", tag: 154),
    Champion(intial: "ㅈ", ko: "제드", en: "Zed", tag: 238),
    Champion(intial: "ㅈ", ko: "직스", en: "Ziggs", tag: 114),
    Champion(intial: "ㅈ", ko: "질리언", en: "Zilean", tag: 26),
    Champion(intial: "ㅈ", ko: "조이", en: "Zoe", tag: 142),
//    Zyra 143
  ]
  
}
